- analysis_xsecQ.C
- analysis_xsecQ_OLD.C
- postprocess_xsecQ.C
- src/Analysis.cxx
- src/Analysis.h
- src/BinSet.cxx
- src/BinSet.h
- src/CutDef.cxx
- src/Histos.cxx
- src/PostProcessor.cxx
- src/PostProcessor.h
add new class `PostProcessor`, steered by postprocessor macros
NOTE: commit https://github.com/c-dilks/largex-eic/commit/57453bb57581091c1f75118122e6d424b56bebfe should have also been included in this PR, where the `PostProcessor` class was started and we also moved the histogram definitions from `Histos` constructor to `Analysis::Execute()`
> add postprocessor class and macro

- config.mk
- src/Analysis.cxx
- src/Analysis.h
- src/Kinematics.cxx
- src/Kinematics.h
Implementing jet clustering with fastjet and relevant variables. Breit frame jets maybe not necessary for Athena studies, but kinematic reconstruction methods as a bin scheme should probably be included.
> Jetchanges

- src/Analysis.cxx
- src/Analysis.h
- src/LinkDef.h
- src/SimpleTree.cxx
- src/SimpleTree.h
- src/Weights.cxx
- src/Weights.h
Adding support for custom weighting of events.
> Add support for weights

- src/Kinematics.cxx
- src/Kinematics.h
close https://github.com/c-dilks/largex-eic/issues/16
> fix jets loop leak

- .gitmodules
- README.md
- analysis_test_SimpleTree.C
- src/Analysis.cxx
- src/Kinematics.cxx
- src/Kinematics.h
add fake asymmetry injection, by spin assignment, for fit code validation
> fake asymmetry injection

- macro/postprocess_pTvsEta.C
- src/Kinematics.h
- src/PostProcessor.cxx
- src/PostProcessor.h
see https://github.com/c-dilks/largex-eic/pull/11
> cherry pick from coverage-studies branch

- src/Kinematics.cxx
close https://github.com/c-dilks/largex-eic/issues/23
> update crossing angle implementation in `Kinematics`

- .github/workflows/ci.yml
- container/ci/macro/analysis_xqbins.C
- container/ci/macro/files.config
- container/ci/macro/postprocess_xqbins_draw.C
- datarec/example.config
- datarec/tutorial.config
- macro/analysis_PvsEta.C
- macro/analysis_asymmetry.C
- macro/analysis_coverage.C
- macro/analysis_fullsim.C
- macro/analysis_purity.C
- macro/analysis_yRatio.C
- src/Analysis.cxx
- src/Analysis.h
- src/AnalysisDD4hep.cxx
- src/AnalysisDelphes.cxx
- tutorial/README.md
- tutorial/analysis_coverage.C
- tutorial/analysis_dd4hep.C
- tutorial/analysis_qbins.C
- tutorial/analysis_template.C
- tutorial/analysis_testDAG.C
- tutorial/analysis_xqbins.C
- tutorial/analysis_yRatio.C
- tutorial/postprocess_coverage.C
- tutorial/postprocess_qbins_tables.C
- tutorial/postprocess_testDAG.C
- tutorial/postprocess_xqbins_draw.C
- tutorial/postprocess_yRatio.C
Use a configuration file to combine multiple Delphes output files with different Q squared cuts.
> Q2 weighting

- src/Analysis.cxx
- src/AnalysisDD4hep.cxx
- src/AnalysisDelphes.cxx
- src/Kinematics.cxx
- src/Kinematics.h
- src/SimpleTree.cxx
- src/Weights.cxx
We want to inject longitudinal asymmetries, so longitudinal polarizations need to be supported.
> Update kinematics to support longitudinal polarization

- macro/analysis_coverage.C
- src/Analysis.cxx
- src/Histos.cxx
- src/Histos.h
Added proton tracks, updated coverage macro, and added a second DefineHist2D function to allow for custom binning (useful to have bins in eta covering exactly barrel/endcaps)
> Proton tracks

- macro/ci/s3files.list
- src/AnalysisDD4hep.cxx
- allow only one file from S3 (to workaround https://github.com/c-dilks/largex-eic/issues/69)
- move histogram/tree filling to inside hadron loop
> update CI for full simulation

- macro/ci/analysis_dd4hep.C
- macro/ci/s3files.list
- src/AnalysisDD4hep.cxx
- src/AnalysisDD4hep.h
- tutorial/analysis_dd4hep.C
- tutorial/s3files.list
Full simulation analyzer update:
- Need mcparticles and ReconstructedParticles branch
- Using ReconstructedParticles branch now to collect all reco particles and use mcID to find matching truth information.
- Tested with canyonlands output:
canyonlands-v1.1/CI/DIS/NC_hepmc2/18x275/minQ2=1/pythia8NCDIS_18x275_minQ2=1_beamEffects_xAngle=-0.025_hiDiv_1.root
> Fullsim update

- s3tools/make-canyonlands-config.sh
- src/AnalysisDD4hep.cxx
close https://github.com/c-dilks/largex-eic/issues/85
> fix maxEvents limiter bug in `AnalysisDD4hep`

- src/AnalysisDD4hep.cxx
close https://github.com/c-dilks/largex-eic/issues/84
this PR applies https://github.com/c-dilks/largex-eic/pull/53 to `AnalysisDD4hep`
> add beam effects to true Kinematics

- .github/workflows/ci.yml
- macro/ci/analysis_p_eta.C
- macro/ci/analysis_x_q2.C
- macro/ci/postprocess_p_eta.C
- macro/ci/postprocess_x_q2.C
- src/AnalysisDelphes.cxx
> add (p,eta) plot grid benchmarks

- .github/workflows/ci.yml
- exeDelphes.sh
- s3tools/README.md
- s3tools/generate-hepmc-list.sh
- s3tools/make-fastsim-config.sh
stream hepmc file from S3 and run through `Delphes`
> add Delphes job

- src/AnalysisDelphes.cxx
> disable hard eta and p cuts in AnalysisDelphes::getPID

- src/AnalysisDelphes.cxx
- src/AnalysisDelphes.h
- src/Kinematics.cxx
- src/Kinematics.h
- update `cards` submodule for DIRC
- add BTOF to `getPID` etc. (close #107 )
> update DIRC and add BTOF

- src/Analysis.cxx
- src/Analysis.h
- src/AnalysisDD4hep.cxx
- src/AnalysisDelphes.cxx
> resolve: cuts are not being applied to SimpleTree

- .github/workflows/ci.yml
- .gitignore
- s3tools/make-canyonlands-config.sh
add limit argument to limit the number of files downloaded or streamed
from S3
> add limiter to s3tools/make-canyonlands-config.sh

- .github/workflows/ci.yml
- macro/ci/merge-fastfull.sh
- macro/ci/merge-recon.sh
- s3tools/generate-hepmc-list.sh
> resolve:  refactor CI, separating analysis and postprocessor jobs #125 

- .github/workflows/ci.yml
for speeding up CI; close #127
> switch from streaming to downloading fullsim files

- .github/workflows/ci.yml
- .gitignore
- macro/ci/analysis_x_q2.C
- macro/ci/comparator.C
- macro/ci/compare_x_q2.C
- macro/ci/flatten-artifacts.sh
- macro/ci/localtest.sh
- macro/ci/merge-fastfull.sh
- macro/ci/merge-recon.sh
- macro/ci/postprocess_p_eta.C
- macro/ci/postprocess_x_q2.C
- src/HistosDAG.cxx
- src/HistosDAG.h
- src/NodePath.h
- src/PostProcessor.cxx
- src/PostProcessor.h
> add comparator

- .github/workflows/ci.yml
- macro/ci/postprocess_p_eta.C
- macro/ci/postprocess_x_q2.C
remove:
- `results_resolution_*`
- `results_coverage_*`, but keep 2D plots and rename to `results_coverage2D_`
> ci: remove redunant artifacts 

- src/AnalysisEcce.cxx
- src/AnalysisEcce.h
> fix: select on `track_source` in `AnalysisEcce`

- datarec/xsec/xsec.dat
- s3tools/make-ecce-config.sh
No
Normalization of first simulation campaign weights will change slightly
> Rcs eicsmearfiles xseclist

- .github/workflows/ci.yml
- datarec/xsec/xsec.dat
- macro/ci/analysis_p_eta.C
- macro/ci/analysis_x_q2.C
- macro/ci/analysis_yRatio.C
- macro/ci/comparator.C
- macro/ci/merge-fastfull.sh
- s3tools/make-athena-config.sh
- s3tools/make-ecce-config.sh
- s3tools/make-fastsim-local-config.sh
- s3tools/read-xsec-table.sh
- src/Analysis.cxx
- src/AnalysisDelphes.cxx
- src/PostProcessor.cxx
> ci: add workflow for `AnalysisEcce`

- macro/depolarization/analysis_depolarization.C
- macro/depolarization/combine_depolarization_plots.rb
- macro/depolarization/postprocess_depolarization.C
- src/Analysis.cxx
Add plots of depolarization vs. y
No
No
> feat: add depolarization vs. y plots

- s3tools/README.md
- tutorial/README.md
Clarify documentation for new `S3` clients
no
no
> doc: clarify S3 access

- doc/kinematics.md
- src/Analysis.cxx
- src/Analysis.h
- src/AnalysisDelphes.cxx
- src/Kinematics.cxx
- src/Kinematics.h
- tutorial/analysis_jets.C
- tutorial/analysis_template.C
- Add macro control to choose jet algo, radius, min pT
- Add additional jet based binning schemes
- Create function to find truth level jet matching a given reco jet
- Add resolution and other histograms
> Jet functionality updates for Delphes 

- .github/workflows/ci.yml
- macro/ci/analysis_p_eta.C
- macro/ci/analysis_x_q2.C
- macro/ci/analysis_yRatio.C
- macro/ci/comparator.C
- src/PostProcessor.cxx
- add EPIC histograms to CI, so we have a 4-way comparison with ECCE, ATHENA, and Delphes
no
no
> ci: add `AnalysisEpic` comparison plots

- doc/example.config
- s3tools/add-host.sh
- s3tools/generate-s3-list.sh
> feat: update S3 endpoint

- .github/workflows/ci.yml
**NOTE:** Incresed beam energy to 18x275
Update CI to use 22.11.3
no
no
> ci: use new 22.11.3 SIDIS production

- .gitmodules
- config.mk
- deps/install_pybind.sh
Default to `eic-shell` `pybind11` installation; PR targets #214 
no
no
> build(HFSimpleTree): remove `pybind11` submodule

- .github/workflows/ci.yml
- s3tools/s3tool.rb
- s3tools/src/loop_run_delphes.sh
Add Pythia6 files from @rseidl-rcf to S3 automation tools (`s3tools/`).
Close #213 
no
only on CI
> feat: add Pythia 6 `hepmc` files to `s3tool`

- s3tools/s3tool.rb
- src/Analysis.cxx
As suggested by @rseidl-rcf, use relative resolution instead of absolute resolution in CI plots.
no
no
> ci: use relative resolution rather than absolute resolution

- macro/depolarization/analysis_depolarization.C
- macro/depolarization/draw_Q2vsX.rb
- macro/depolarization/postprocess_depolarization.C
- src/PostProcessor.h
- Add Q2 vs. x distribution with y-contours
- Add uncertainty impact plot: 1 / sqrt(N) * depolarization factor
no
no
> feat: add uncertainty impact plots from depolarization

- config.mk
Allows overriding CXX via `make CXX=foo`
> config.mk: allow overriding CXX

- .github/workflows/ci.yml
Compile with optimization
no
no
> ci: run with optimized build

- macro/depolarization/analysis_depolarization.C
- macro/depolarization/draw_Q2vsX.rb
- macro/depolarization/postprocess_depolarization.C
Update depolarization vs. Q2 vs. x plots for ePIC, along with statistical impact
no
no
> feat: update depolarization plots for ePIC

- .github/workflows/ci.yml
- macro/ci/analysis_q2_weights.C
- macro/ci/postprocess_q2_weights.C
- src/PostProcessor.cxx
We need to be testing the Q2 weights more regularly, since they not be correct for some datasets. 
no
no
> ci: draw Q2 distributions to check Q2 weights

- deps/adage/.gitrepo
- deps/adage/src/BinSet.cxx
- deps/adage/src/DAG.cxx
- deps/adage/src/Node.cxx
- src/Analysis.cxx
- src/Analysis.h
- src/AnalysisAthena.cxx
- src/AnalysisDelphes.cxx
- src/AnalysisEcce.cxx
- src/AnalysisEpic.cxx
- src/AnalysisEpicPodio.cxx
- src/HFSTree.cxx
- src/HFSTree.h
- src/Hist4D.cxx
- src/Hist4D.h
- src/Histos.cxx
- src/Kinematics.cxx
- src/Kinematics.h
- src/ParticleTree.h
- src/PostProcessor.h
- src/SimpleTree.cxx
- src/SimpleTree.h
Fix various memory leaks
no
no
> fix: memory leaks

- .github/workflows/ci.yml
- .gitignore
- macro/ci/valgrind_check.sh
- s3tools/src/truncate-config-file.rb
Add `valgrind` memory check to CI; this should help find our slow memory leak
no
no
> ci: run `valgrind` memcheck

- .github/workflows/ci.yml
- datarec/xsec/xsec.dat
- hpc/src/count_events.cpp
- macro/ci/comparator.C
- s3tools/README.md
- s3tools/s3tool.rb
- src/Analysis.cxx
- tutorial/README.md
- tutorial/analysis_epic.C
- tutorial/analysis_jets.C
- tutorial/analysis_template.C
Rename to ePIC in documentation and CI plots.
no
no
> doc: EPIC -> ePIC

- README.md
- macro/binning.C
- s3tools/README.md
- src/SimpleTree.cxx
- tutorial/README.md
- tutorial/analysis_athena.C
- tutorial/analysis_epic.C
- tutorial/analysis_eventEvaluator.C
- tutorial/analysis_template.C
Make the documentation more presentable as a tutorial
no
no
> doc: streamline documentation for tutorial presentation

- .github/workflows/ci.yml
We were setting both `--mode s` and `--mode d`; fortunately `--mode s` was the one that has been running all this time, which is preferred.
no
no
> ci: fix conflicting `mode` setting for `download_fullsim`

- README.md
- macro/analysis_asymmetry.C
- macro/analysis_purity.C
- macro/analysis_testml.C
- macro/ci/analysis_p_eta.C
- macro/ci/analysis_q2_weights.C
- macro/ci/analysis_x_q2.C
- src/Analysis.cxx
- src/Analysis.h
- src/AnalysisAthena.cxx
- src/AnalysisDelphes.cxx
- src/AnalysisEcce.cxx
- src/AnalysisEpic.cxx
- src/AnalysisEpicPodio.cxx
- src/Kinematics.h
- src/LinkDef.h
- src/SidisTree.cxx
- src/SidisTree.h
- tutorial/analysis_athena.C
- tutorial/analysis_epic.C
- tutorial/analysis_eventEvaluator.C
- tutorial/analysis_jets.C
- tutorial/analysis_template.C
- tutorial/analysis_yRatio.C
close #256
maybe, but unlikely
no
> refactor: rename `SimpleTree` -> `SidisTree`

- .github/workflows/ci.yml
- macro/ci/analysis_single_bin.C
- macro/ci/postprocess_eta_vs_p_forPID.C
Add eta vs. p plot to CI, to show what this looks like for SIDIS pions (for @chchatte92)
no
no
> ci: add eta vs. p plot for PID coverage checks

- deps/README.md
- deps/adage/.gitrepo
- deps/adage/include/adage/Adage.h
- deps/adage/include/adage/BinSet.h
- deps/adage/include/adage/CutDef.h
- deps/adage/include/adage/DAG.h
- deps/adage/include/adage/Node.h
- deps/adage/include/adage/NodePath.h
- src/Analysis.h
- src/AnalysisAthena.h
- src/AnalysisDelphes.h
- src/AnalysisEcce.h
- src/AnalysisEpic.h
- src/DataModel.h
- src/HFSTree.h
- src/Histos.h
- src/HistosDAG.h
- src/Kinematics.h
- src/KinematicsJets.h
- src/ParticleTree.h
- src/PostProcessor.h
- src/SidisTree.h
`#include "some/external/header.h"` -> `#include <some/external/header.h>`
no
no
> fix: external include directives should use angled brackets

- .github/workflows/ci.yml
- s3tools/s3tool.rb
Add production 23.05.2 to `s3tool`
no
no
> feat: support production 23.05.2
