eic/epic-analysis

macro/analysis_asymmetry.C
src/Kinematics.cxx
src/Kinematics.h
src/SimpleTree.cxx
tutorial/analysis_template.C

close https://github.com/c-dilks/largex-eic/issues/14
depolarization calculations:
https://github.com/c-dilks/largex-eic/blob/f1508ec586cd20374fc2d1346dce66d45e79e37b/src/Kinematics.cxx#L113-L131
These calculations should be double checked (added to the list in https://github.com/c-dilks/largex-eic/issues/28)
- depolarization calculations are performed in `Kinematics::CalculateDIS`
- implemented in `Kinematics`, `SimpleTree`, and fit code submodule; validated with fake asymmetry injection
- boost vector calculations moved to  `Kinematics::CalculateDIS`

add depolarization calculations

---

macro/ci/postprocess_resolution.C
src/BinSet.cxx
src/BinSet.h
src/DAG.cxx
src/Node.cxx
src/Node.h
src/NodePath.cxx
src/NodePath.h

- add `BinSet::GetMin()` and `BinSet::GetMax()`, to access the minimum and maximum of a set of bins
- add `binNum` to `Node`, to store a bin number in a bin node; add accessor and modifier `Node::Get/SetBinNum()`
- add `NodePath::BinListName()` to return a convenient string giving a unique name for the list of bin nodes in the `NodePath`; this can be used to make unique names for `TCanvas` etc.
- bin numbers are now assigned in `DAG::AddLayer`, which is the main method used to add `BinSet` layers to the DAG, and is called by `HistosDAG::Build`
- update `macro/ci/postprocess_resolution.C` to make use of all above changes, and help support `PostProcessor::DrawInBins`; these updates will facilitate the production of resolution and coverage proposal plots @mfmceneaney @cpecar 
close …

add bin number access to NodePath

---

.github/workflows/ci.yml
macro/analysis_PvsEta.C
macro/analysis_asymmetry.C
macro/analysis_coverage.C
macro/analysis_phi_crosscheck.C
macro/analysis_purity.C
macro/ci/analysis_xq.C
src/Kinematics.cxx
tutorial/analysis_coverage.C
tutorial/analysis_dd4hep.C
tutorial/analysis_qbins.C
tutorial/analysis_template.C
tutorial/analysis_testDAG.C
tutorial/analysis_xqbins.C
tutorial/analysis_yRatio.C

close https://github.com/c-dilks/largex-eic/issues/89
- now it does not matter which sign is used at the macro level
- macro default args have been updated anyway

enforce correct crossing angle sign

---

macro/ci/analysis_xq.C
src/AnalysisDD4hep.cxx

close #81 
- add counter to check how many times proximity matching is invoked
- tests on a small sample indicate this never happens
- warning printed for nonzero counts

add proximity match attempts counter

---

.github/workflows/ci.yml
.gitignore
macro/ci/analysis_p_eta.C
macro/ci/analysis_x_q2.C
macro/ci/organize-artifacts.sh
macro/ci/postprocess_x_q2.C
src/Analysis.cxx
src/AnalysisDD4hep.cxx
src/AnalysisDelphes.cxx
src/Kinematics.cxx
src/Kinematics.h

tries to address https://github.com/c-dilks/largex-eic/issues/110, but does not resolve
Instead, several small updates are implemented:
- in some places, there was some inconsistency of which frame the calculation was being performed in; in general, however, the difference between lab frame and head-on frame seems subdominant compared to the large difference in resolutions between electronic and hadronic methods
- add more resolution plots, and fix some axis ranges:
- Nu
- W
- z
- mX
- xF
- rename `Kinematics::getqWQuadratic` to `Kinematics::GetQWNu_quadratic` and add two additional methods which serve the same purpose of calculating the components of q, W, and Nu:
- `GetQWNu_electronic`, used by electron and mixed recon methods
- `GetQWNu_hadronic`, which was an attempt to compare to …

debug JB and DA issue

---

exeDelphes.sh
macro/ci/analysis_x_q2.C
macro/ci/postprocess_x_q2.C
s3tools/README.md
s3tools/make-canyonlands-config.sh
s3tools/make-fastsim-S3-config.sh
s3tools/make-fastsim-config.sh
src/AnalysisDelphes.cxx

add some scripts, in particular `s3tools/make-fastsim-S3-config.sh`, to
automate downloading `hepmc` files from S3, running Delphes on them, and
generate the config file.
close https://github.com/c-dilks/largex-eic/issues/94

automate delphes for S3 hepmc files

---

.github/workflows/ci.yml
src/PostProcessor.cxx

change normalization of compared histograms in DrawInBins to be via
histogram integrals, rather than by histogram maxima

normalize comparator hists by integral

---

.github/workflows/ci.yml
README.md

Uses `apt` caching, which should speed up our pipelines

ci: update `github-action-cvmfs` to v3

---

.github/workflows/ci.yml
Makefile
README.md
config.mk
macro/ci/analysis_p_eta.C
macro/ci/analysis_x_q2.C
macro/ci/analysis_yRatio.C
macro/ci/include_delphes.C
src/Analysis.cxx
src/Analysis.h
src/AnalysisDelphes.cxx
src/Kinematics.cxx
src/Kinematics.h
src/LinkDef.h
src/Makefile

This allows for `libSidis-eic` builds without Delphes dependence, which
will significantly reduce the size of build artifacts, and hopefully
speed up workflows a bit more.

ci: add build flag `EXCLUDE_DELPHES`

---

.github/workflows/ci.yml
config.mk
macro/ci/analysis_p_eta.C
macro/ci/analysis_x_q2.C
macro/ci/analysis_yRatio.C
macro/ci/define_exclude_delphes.C
macro/ci/include_delphes.C
src/Analysis.cxx
src/Analysis.h
src/Kinematics.cxx
src/Kinematics.h
src/LinkDef.h
src/Makefile

ROOT macros typically do not `#define INCLUDE_DELPHES`, except those for CI; therefore `#ifdef INCLUDE_DELPHES` is false by default. This explains why sporadic crashes of #174 were occurring locally, but not in CI workflows. This PR switches to using `#ifndef EXCLUDE_DELPHES`, since that will be true by default.

fix:  macros do not `#define INCLUDE_DELPHES`; switch to `#ifndef EXCLUDE_DELPHES`

---

macro/depolarization/analysis_depolarization.C
src/Analysis.cxx
src/Analysis.h
src/AnalysisAthena.cxx
src/AnalysisDelphes.cxx
src/AnalysisEcce.cxx
src/Histos.cxx
src/Histos.h
tutorial/analysis_dd4hep.C
tutorial/analysis_eventEvaluator.C
tutorial/analysis_template.C

Add `includeOutputSet` settings in `Analysis`, to control what to include in the output. This will allow us to turn on/off large sets of plots or tree branches, along with certain parts of the `Analysis` subclass event loops. For example, we can now implement a dihadron analysis which will only run if a macro tells it to.
No
No

feat: control what is included in the output data structures

---

macro/analysis_PvsEta.C
macro/analysis_coverage.C
macro/analysis_purity.C
src/Analysis.cxx
src/AnalysisDelphes.cxx
tutorial/analysis_coverage.C
tutorial/analysis_dd4hep.C
tutorial/analysis_epic.C
tutorial/analysis_eventEvaluator.C
tutorial/analysis_qbins.C
tutorial/analysis_template.C
tutorial/analysis_xqbins.C
tutorial/analysis_yRatio.C

- this removes the need for the user to call `AddFinalState` for jets
- also renames jet variables, to group them together

fix: create `jet` final state when included in output

---

src/AnalysisEpicPodio.cxx
src/AnalysisEpicPodio.h
src/LinkDef.h

Preserve `PODIO` collection dependent version of `AnalysisEpic` as `AnalysisEpicPodio`, to be ready for when `EICrecon` has full `PODIO`-compliant output available.
no
no

chore: rename `AnalysisEpic` -> `AnalysisEpicPodio`

---

src/Analysis.cxx

Any `TFile` which is opened with `TFile::Open()` will create a pointer that will not be automatically deleted, does not like to be wrapped by a smart pointer, and may not be fully closed by `TFile::Close()` when streaming from S3. 
Thanks to @rseidl-rcf for finding and fixing this bug!
Hopefully this resolves our `exit 13` mystery in #232 
no
no

fix: `delete` any `TFile` pointer created by `TFile::Open()`

---

.github/workflows/ci.yml
src/AnalysisAthena.cxx
src/AnalysisDelphes.cxx
src/AnalysisEcce.cxx
src/AnalysisEpic.cxx

- minimize runner disk usage by streaming from S3 instead of downloading
- if we want, this allows us to maximize the statistics, since the limit becomes the 6 hour job limit, rather than the ~14GB runner disk space limit
- test statistics size and CI runtime remain the same
no
no

ci: use S3 streaming

---

Makefile
src/Kinematics.h

Some `pybind` headers were still included in `Kinematics.h`; this PR ensures macro `SIDIS_MLPRED` controls their inclusion.
Fixes runtime error: https://github.com/eic/epic-analysis/actions/runs/4346053472/jobs/7591698317
no
no

fix: make `pybind` inclusion optional

---

.gitignore
Makefile
README.md
hpc/README.md
hpc/merge.rb
hpc/prepare.rb
hpc/run-local-condor.rb
hpc/run-local-slurm.rb
hpc/src/count_events.cpp
hpc/src/merge_analysis_files.cpp
src/Analysis.cxx
src/Analysis.h
src/AnalysisAthena.cxx
src/AnalysisDelphes.cxx
src/AnalysisEcce.cxx
src/AnalysisEpic.cxx
src/Histos.cxx
src/Histos.h

Prepare for running jobs on HPC clusters. The idea is a 3 step procedure: 
1. `hpc/prepare.rb`: split a config file into one config file per ROOT file; these config files can be fed to `Analysis`; total yields per Q2 bin are automatically obtained and stored in all config files, to make sure the resulting Q2 weights are correct for the combined set of files. See #235 for details
2. `hpc/run-local-condor.rb`: prepare a `condor` configuration script to run these config files locally on `condor`; the user must run `condor_submit` externally from `eic-shell` (but jobs will be run in an `eic-shell` instance); this type of script could be extended to support HPC clusters
3. `hpc/merge.rb`: combine the resulting output ROOT files; this is basically `hadd` with some handlers for our custom …

feat: initial support for HPC

---

Makefile
README.md
src/AnalysisEpicPodio.cxx
src/AnalysisEpicPodio.h
src/LinkDef.h
tutorial/podio_datatypes.C

This removes the `EventStore` deprecation warnings, until we can full transition to PODIO frames. PODIO support will now be disabled by default.
no
no

build: make build with `PODIO` optional

---

.github/workflows/ci.yml

Use non-radiative-corrected data for fast simulation CI tests (because of https://github.com/eic/epic-analysis/issues/248)
no
no

ci: use `--no-radcor` for fastsim tests

---

s3tools/s3tool.rb

`s3tool` support for latest 2023 production versions.
Newer productions may not have as much data as older versions, so leaving the default production version as is: `22.11.3`. Use `s3tool.rb -v` to try later versions.
Tests:
no
no

feat: support productions `23.01` and `23.03`

---

.github/workflows/ci.yml
s3tools/s3tool.rb

Sometimes it's useful to drink directly from the simulation production firehose
Add new production version `epic.unstable`, which we can change as needed to test the bleeding edge of production. Typically only small samples appear here, and `epic.unstable` as a production version is not always guaranteed to work (it depends on when we test and what is on disk).
no
no

feat: add `epic.unstable` testing version to `s3tool.rb`

---

tutorial/podio_print_collection_datatypes.C

Remove unnecessary warning
no
no

fix: remove warning about missing collections in `podio_print_collection_datatypes.C`

---

.github/workflows/ci.yml
s3tools/s3tool.rb
src/AnalysisEpic.cxx

Support production 23.05.01. This production also has a TTree branch name change:
```
ReconstructedChargedParticlesAssociations -> ReconstructedChargedParticleAssociations
```
To maintain backward compatibility with previous productions, `AnalysisEpic` now includes a check to determine which branch name to use.

feat: support production 23.05.1

---

macro/analysis_makeHFStree.C
src/AnalysisAthena.cxx
src/AnalysisDelphes.cxx
src/AnalysisEcce.cxx
src/AnalysisEpic.cxx
src/HFSTree.cxx
src/Kinematics.cxx
src/Kinematics.h

For ease of SIDIS kinematic reconstruction studies, added the matched true track momentum to the output of HFS tree. This isn't the full true hadronic final state, just the true momenta of reconstructed tracks.
Also added a different function to fill HFSTree variables. Was previously included as part of Kinematics::AddToHFS
No.
No.

Added matched true track kinematics to reconstructed HFS particles to HFSTree

---

.github/workflows/ci.yml
s3tools/s3tool.rb

23.05.02 is the large-statistics May 2023 production. Update to this default in `s3tool.rb`. Additionally update the default in CI (by simply removing the `--version` specification).
No
No, but this is a new default production.

feat: update default production version to 23.05.2

---

.github/workflows/ci.yml
s3tools/s3tool.rb
src/Analysis.cxx
src/PostProcessor.cxx

- Support production 23.06.1
- Set eta vs. p plot to log scale (for PID review)
- CI: change ePIC `arches` vs. `brycecanyon` comparisons to be `latest` production vs. `previous` production
- `latest` and `previous` is set in `s3tool.rb`
- disable legacy comparisons
- this was motivated by `brycecanyon` now being the primary focus for productions
no
yes, new default production

feat: support production 23.06.1

---

s3tools/s3tool.rb

-Adds EPIC 23.07.1 support to s3tool 
-Changes default EPIC configuration to brycecanyon
No.
Yes, default s3tool.rb behavior changes slightly. Versions of EPIC full simulation used in CI will be updated.

Support epic 23.07.1
